plugins {
	id "fabric-loom" version "1.6-SNAPSHOT"
	id 'net.darkhax.curseforgegradle' version '1.1.18'
}

archivesBaseName = "DefaultSettings"

def file_version = "4.0.7";

version = "1.21.4-${file_version}-Fabric"

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

jar {
     manifest {
            attributes([
                    "Implementation-Version" : "${file_version}"
            ])
        }
}

dependencies {
	minecraft "com.mojang:minecraft:1.21"
	mappings loom.officialMojangMappings()

	modImplementation "net.fabricmc:fabric-loader:0.15.11"

	modImplementation "net.fabricmc.fabric-api:fabric-api:0.100.1+1.21"

	modImplementation "curse.maven:jcp-659192:4430988"
	//implementation project(":Core")
}

java {
	//withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

processResources {
	inputs.property "version", file_version
	inputs.property "JCPluginVersion", "4.0.4"

	filesMatching(["**/fabric.mod.json", "**/mods.toml"]) {
		expand "version": file_version, "JCPluginVersion": "4.0.4"
	}
}

tasks.withType(JavaCompile).configureEach {
	//source(project(":Core").sourceSets.main.allSource)
}

loom {

	accessWidenerPath = file("src/main/resources/defaultsettings.accesswidener")

	runs {
		client {
			client()
			setConfigName("Fabric 1.21.4 Client")
			ideConfigGenerated(true)
			runDir("./run")
		}
		server {
			server()
			setConfigName("Fabric 1.21.4 Server")
			ideConfigGenerated(true)
			runDir("./run")
		}
	}

	//mixin {
	//	defaultRefmapName = "${project.rootProject.name}.refmap.json"
	//}
}

//java {
//	withSourcesJar()
//}

task sourcesJar(type: Jar) {
	from sourceSets.main.allSource
	//from(project(":Core").sourceSets.main.allSource)
	archiveClassifier = 'sources'
}

artifacts {
	archives jar
	archives sourcesJar
}

/*task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
	dependsOn "build"
	if (System.getenv("CURSE_API") != null && !System.getenv("CURSE_API").equals("")) {
		disableVersionDetection()
		apiToken = System.getenv("CURSE_API")

		def mainFile = upload(451860, remapJar.archiveFile)
		mainFile.releaseType = project.ext.relType
		mainFile.displayName = "$archivesBaseName-$version"
		mainFile.changelogType = 'html'
		mainFile.changelog = file('../../changelog.html')
		mainFile.addRequirement('jcplugin')
		mainFile.addModLoader('Fabric')
		mainFile.addJavaVersion('Java 17')
		mainFile.addGameVersion('Client')
		mainFile.addGameVersion('1.20.4')
		mainFile.addGameVersion('1.20.3')
		mainFile.addGameVersion('1.20.2')
		mainFile.addGameVersion('1.20.1')
		mainFile.addGameVersion('1.20')

		def sourcesFile = mainFile.withAdditionalFile(sourcesJar)
		sourcesFile.changelog = file('../../changelog.html')
		sourcesFile.addRequirement('jcplugin')
		sourcesFile.displayName = "$archivesBaseName-$version-sources"
	}
}*/

task("copyRelease") {
	dependsOn "build"

	doFirst {
		println "Gathering builds"
		copy {
			def libDir = project.projectDir.toPath().resolve("build/libs")
			from(libDir) {
				include "*.jar"
				exclude "*-dev.jar", "*-sources.jar"
			}
			into "../../build/libs/"
			duplicatesStrategy DuplicatesStrategy.INCLUDE
		}
	}
}