name: Publish CI

on:
  workflow_dispatch:
    inputs:
      publish-all:
        type: boolean
        description: 'Should all editions be published?'
        required: true
        default: false
      publish-edition:
        description: 'Edition to publish (Forge-1.16.5 or Fabric-1.16.5)'
        required: false
        default: 'Forge-1.16.5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle and publish all editions
        if: ${{ github.event.inputs.publish-all == 'true' }}
        run: ./gradlew build publishCurseForge copyRelease
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
      - name: Build with Gradle and publish specific edition
        if: ${{ github.event.inputs.publish-all == 'false' }}
        run: ./gradlew :${{ github.event.inputs.publish-edition }}:build :${{ github.event.inputs.publish-edition }}:publishCurseForge :${{ github.event.inputs.publish-edition }}:copyRelease
        env:
          CURSE_API: ${{ secrets.CURSE_API }}
      - uses: actions/upload-artifact@v2
        with:
          name: 'Prebuilt Artifacts'
          path: build/libs